// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as $$Promise from "../node_modules/@ryyppy/rescript-promise/src/Promise.mjs";
import * as Caml_exceptions from "../node_modules/rescript/lib/es6/caml_exceptions.js";

var AnError = /* @__PURE__ */Caml_exceptions.create("Catch.AnError");

Zora.test("should catch failures", (function (t) {
        t.test("Promise Rejection", (function (t) {
                return $$Promise.$$catch(Promise.reject({
                                  RE_EXN_ID: AnError,
                                  _1: "Things not good"
                                }).then(function (param) {
                                return Promise.resolve((t.fail("Should not enter then clause"), undefined));
                              }), (function (param) {
                              return Promise.resolve((t.ok(true, "The promise did reject"), undefined));
                            }));
              }));
      }));

export {
  AnError ,
}
/*  Not a pure module */
